# The name of your project/route.
# This will be displayed in the header for people who are viewing your route
title: All Women (1.1)

# The version of your route. There's no particular format here.
# This will be displayed in the metadata in the settings dialog
version: 1.1.1

# This is the route itself. Here it points to the main.yaml file we created earlier
route:
  use: ./main.yaml

# Extra configuration.
# The project must define a map to compile properly.
# For now, we will use the Breath of the Wild celer map maintained by Pistonight
config:
  - use: Pistonight/celer-presets/botw/map.yaml
  - plugins:
      - use: link
      - use: variables
  - icons:
      shrine: https://icons.pistonite.org/icon/shrine.shrine.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      tower: https://icons.pistonite.org/icon/location.tower.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      woman: https://icons.pistonite.org/icon/character.zelda.none.8c5e28.ffffb5.8c5e28.fdfdfd.8c5e28.fdfdfd.png
      road-woman: https://icons.pistonite.org/icon/character.zelda.triangle.69a2d5.ffffb5.8c5e28.fdfdfd.69a2d5.c1fefe.png
      shopkeeper-woman: https://icons.pistonite.org/icon/character.zelda.square.d57b69.fdfdfd.8c5e28.ffffb5.d57b69.fdfdfd.png
      special-woman: https://icons.pistonite.org/icon/character.zelda.circle.f24c99.ffc0fa.8c5e28.ffffb5.f24c99.ffc0fa.png
      attacked-woman-minus: https://icons.pistonite.org/icon/character.zelda.minus.613b75.b96cf5.8c5e28.ffffb5.613b75.b96cf5.png
      attacked-woman-plus: https://icons.pistonite.org/icon/character.zelda.plus.613b75.b96cf5.8c5e28.ffffb5.613b75.b96cf5.png
      child-woman: https://icons.pistonite.org/icon/character.zelda.none.69a2d5.c1fefe.8c5e28.ffffb5.d57b69.fec1d3.png
      material: https://icons.pistonite.org/icon/misc.apple.none.69a2d5.c1fefe.cfa240.ffd700.69a2d5.c1fefe.png
      weapon: https://icons.pistonite.org/icon/misc.hammer.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      king: https://icons.pistonite.org/icon/character.king.none.cfa240.ffd700.8c5e28.fdfdfd.8c5e28.fdfdfd.png
      marker: https://icons.pistonite.org/icon/misc.frame.none.f24c99.ffc0fa.f24c99.ffc0fa.f24c99.ffc0fa.png
      fire: https://icons.pistonite.org/icon/location.fire_temple.none.d57b69.fec1d3.d57b69.fdfdfd.d57b69.fdfdfd.png
  - presets:
      Material:
        text: Collect $(0)
        comment: $(1) $(0)
        icon: material
      _Woman:
        _Road:
          Watch:
            text: Look for .road($(0)) - $(2)
            comment: on the road between .road($(1))
        Road:
          text: .road($(0)) - $(2)
          comment: attempt to force spawn by saving and cycling reloads at $(1)
          notes:
            - try to save with camera facing many spawn points
            - save within the location area - so it says $(1) on the save file
            - save on a road, if possible
          icon: road-woman
          counter: .var(women)
          vars:
            segment-women: .add(1)
        Shopkeeper:
          text: $(0)
          comment: $(1) merchant
          icon: shopkeeper-woman
          counter: .var(women)
          vars:
            segment-women: .add(1)
        Child:
          text: $(0)
          comment: say hi to the child
          icon: child-woman
          counter: .var(women)
          vars:
            segment-women: .add(1)
        Special:
          text: $(0)
          icon: special-woman
          counter: .var(women)
          vars:
            segment-women: .add(1)
        _Attacked:
          Armed:
            text: $(0)
            comment: get 'em sis!
            icon: attacked-woman-plus
            counter: .var(women)
            vars:
              segment-women: .add(1)
          Unarmed:
            text: $(0)
            comment: she's under attack! help her!
            icon: attacked-woman-minus
            counter: .var(women)
            vars:
              segment-women: .add(1)
      Woman:
        text: $(0)
        comment: say hi
        icon: woman
        counter: .var(women)
        vars:
          segment-women: .add(1)
      Segment:
        text: $(0) [.var(segment-women) of .var(women)]
        counter: .var(segment)
      Fire:
        text: Wait til $(0)
        icon: fire
  - splits:
      - segment
  - tags:
      segment:
        color: pink
        background: purple
        split-type: Segment
      sub:
        color: grey
      todo:
        background: magenta
      road:
        color: black
        background: palegoldenrod
      important:
        color: white
        background: red
      place:
        color: cyan
      segment-women:
        color: purple
        background: pink
      women:
        color: purple
        background: pink
        split-type: Women
